version: '3'

services:
  frontend:
    image: nginx:alpine
    networks:
      - network_public

  supabase:
    image: supabase/postgres:15.1.0.117
    environment:
      - POSTGRES_PASSWORD=your-password
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
    volumes:
      - supabase_data:/var/lib/postgresql/data
    networks:
      - network_public

  redis:
    image: redis:7-alpine
    volumes:
      - redis_data:/data
    networks:
      - network_public

volumes:
  supabase_data:
  redis_data:

networks:
  network_public:
    external: true 